// NetBeans IDE 26
// Nome: Joao Pedro Dias Elero - RA: 2706431
import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {
    
    private static FormPrincipal formPrincipalUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static FormPrincipal getformPrincipalUnic(){
        if(formPrincipalUnic == null){
            formPrincipalUnic = new FormPrincipal();
        }
        return formPrincipalUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelRa = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        mnItCadEst = new javax.swing.JMenuItem();
        mnItCadCoo = new javax.swing.JMenuItem();
        mnItCadMot = new javax.swing.JMenuItem();
        mnItCadFac = new javax.swing.JMenuItem();
        mnItCadVei = new javax.swing.JMenuItem();
        mnItSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("FormPrincipal");

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSubtitulo.setText("Sistema de Gerenciamento de Transporte Universitário");

        jLabelNome.setText("Nome: João Pedro Dias Elero");

        jLabelRa.setText("RA: 2706431");

        mnCadastro.setText("Cadastros");

        mnItCadEst.setText("Cadastro de Estudantes...");
        mnItCadEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadEstActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItCadEst);

        mnItCadCoo.setText("Cadastro de Coordenador...");
        mnItCadCoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadCooActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItCadCoo);

        mnItCadMot.setText("Cadastro de Motorista...");
        mnItCadMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadMotActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItCadMot);

        mnItCadFac.setText("Cadastro de Faculdade...");
        mnItCadFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadFacActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItCadFac);

        mnItCadVei.setText("Cadastro de Veículo...");
        mnItCadVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadVeiActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItCadVei);

        mnItSair.setText("Sair...");
        mnItSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItSairActionPerformed(evt);
            }
        });
        mnCadastro.add(mnItSair);

        jMenuBar.add(mnCadastro);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelSubtitulo)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelRa))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRa)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItSairActionPerformed
        sair();
    }//GEN-LAST:event_mnItSairActionPerformed

    private void mnItCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadEstActionPerformed
        cadEst();
    }//GEN-LAST:event_mnItCadEstActionPerformed

    private void mnItCadCooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadCooActionPerformed
        cadCoo();
    }//GEN-LAST:event_mnItCadCooActionPerformed

    private void mnItCadMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadMotActionPerformed
        cadMot();
    }//GEN-LAST:event_mnItCadMotActionPerformed

    private void mnItCadFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadFacActionPerformed
        cadFac();
    }//GEN-LAST:event_mnItCadFacActionPerformed

    private void mnItCadVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadVeiActionPerformed
        cadVei();
    }//GEN-LAST:event_mnItCadVeiActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void cadEst(){
        FormEstudante.getFormEstudanteUnic().setVisible(true);
    }
    
    public void cadCoo(){
        FormCoordenador.getFormCoordenadorUnic().setVisible(true);
    }
    
    public void cadMot(){
        FormMotorista.getFormMotoristaUnic().setVisible(true);
    }
    
    public void cadFac(){
        FormFaculdade.getFormFaculdadeUnic().setVisible(true);
    }
    
    public void cadVei(){
        FormVeiculo.getFormVeiculoUnic().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRa;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenuItem mnItCadCoo;
    private javax.swing.JMenuItem mnItCadEst;
    private javax.swing.JMenuItem mnItCadFac;
    private javax.swing.JMenuItem mnItCadMot;
    private javax.swing.JMenuItem mnItCadVei;
    private javax.swing.JMenuItem mnItSair;
    // End of variables declaration//GEN-END:variables
}
