// Modelo: Joao Pedro Dias Elero - RA: 2706431
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormVeiculo extends javax.swing.JFrame {
    private Veiculo v = new Veiculo();
    private BDVeiculo bd = BDVeiculo.getVeiculoUnic();
    
    private static FormVeiculo formVeiculoUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormVeiculo.class.getName());

    /**
     * Creates new form FormVeiculo
     */
    private FormVeiculo() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static FormVeiculo getFormVeiculoUnic(){
        if(formVeiculoUnic == null){
            formVeiculoUnic = new FormVeiculo();
        }
        return formVeiculoUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlaca = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        jLabelModelo = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa");

        jLabelPlaca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelPlaca.setText("Placa:");

        jLabelModelo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelModelo.setText("Modelo:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelPlaca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfModelo)
                            .addComponent(tfPlaca)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPlaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfModelo))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserir();
        lisTab();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        lisTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        lisTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        selTab();
    }//GEN-LAST:event_tabelaMouseClicked

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        tfPlaca.setText("");
        tfModelo.setText("");
        tfPlaca.requestFocus();
    }
    
    public void inserir(){
        try{
            v = new Veiculo();

            v.setPlaca(Integer.parseInt(tfPlaca.getText()));
            v.setModelo(tfModelo.getText());

            v = bd.insereVec(v);

            if(v != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Veiculo cadastrado com sucesso!",
                        "Cadastro de Veiculo",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Essa placa já está cadastrada!",
                        "Cadastro de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "A placa deve ser um número inteiro!",
                        "Cadastro de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
        }
    }
    
    public void consultar(){
        try{
            v = new Veiculo();

            v.setPlaca(Integer.parseInt(tfPlaca.getText()));

            v = bd.consultaVec(v);

            if(v != null){
                tfPlaca.setText(Integer.toString(v.getPlaca()));
                tfModelo.setText(v.getModelo());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Veiculo encontrado!",
                        "Consulta de Veiculo",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Placa não encontrada!",
                        "Consulta de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "A placa deve ser um número inteiro!",
                        "Consulta de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
        }
    }
    
    public void alterar(){
        try{
            v = new Veiculo();

            v.setPlaca(Integer.parseInt(tfPlaca.getText()));

            v = bd.alteraVec(v);

            if(v != null){
                String nome = JOptionPane.showInputDialog(
                        null,
                        "Informe o nome do modelo:",
                        "Alteração de Veiculo",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(nome != null){
                    v.setModelo(nome);
                }
            }
            
            if(v != null){
                tfPlaca.setText(Integer.toString(v.getPlaca()));
                tfModelo.setText(v.getModelo());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Dados alterados!",
                        "Alteração de Veiculo",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Placa não encontrada!",
                        "Alteração de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "A placa deve ser um número inteiro!",
                        "Alteração de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
        }
    }
    
    public void excluir(){
        try{
            v = new Veiculo();

            v.setPlaca(Integer.parseInt(tfPlaca.getText()));

            v = bd.excluiVec(v);

            if(v == null){
                JOptionPane.showMessageDialog(
                        null,
                        "Veiculo excluído com sucesso!",
                        "Exclusão de Veiculo",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Placa não encontrada!",
                        "Exclusão de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            tfPlaca.setText("");
            tfPlaca.requestFocus();
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "A placa deve ser um número inteiro!",
                        "Exclusão de Veiculo - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfPlaca.setText("");
                tfPlaca.requestFocus();
        }
    }
    
    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tabela.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Veiculo p : bd.getBdVec()){
            modTab.insertRow(posLin, new Object[]{p.getPlaca(), p.getModelo()});
            posLin++;
        }
    }
    
    public void selTab(){
        String valLin = "";
        int posLin = tabela.getSelectedRow();
        for(int col = 0 ; col < tabela.getColumnCount() ; col++){
            valLin += tabela.getModel().getValueAt(posLin, col).toString();
        }
        JOptionPane.showMessageDialog(
                null,
                "O valor da linha é: "+ valLin,
                "Captura de tabela",
                1
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormVeiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables
}
