// Nome: Joao Pedro Dias Elero - RA: 2706431
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCoordenador extends javax.swing.JFrame {
    private Coordenador c = new Coordenador();
    private BDCoordenador bd = BDCoordenador.getCoordenadorUnic();
    
    private static FormCoordenador formCoordenadorUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCoordenador.class.getName());

    /**
     * Creates new form FormCoordenador
     */
    private FormCoordenador() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static FormCoordenador getFormCoordenadorUnic(){
        if(formCoordenadorUnic == null){
            formCoordenadorUnic = new FormCoordenador();
        }
        return formCoordenadorUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabelSetor = new javax.swing.JLabel();
        tfSetor = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estudante");

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCpf.setText("CPF:");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNome.setText("Nome:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Setor", "Email"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabelSetor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSetor.setText("Setor:");

        tfSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSetorActionPerformed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelEmail.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelCpf)
                            .addComponent(jLabelSetor)
                            .addComponent(jLabelEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addComponent(tfCpf)
                            .addComponent(tfSetor)
                            .addComponent(tfEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSetor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmail))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserir();
        lisTab();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        lisTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        lisTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        selTab();
    }//GEN-LAST:event_tabelaMouseClicked

    private void tfSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSetorActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        tfCpf.setText("");
        tfNome.setText("");
        tfSetor.setText("");
        tfEmail.setText("");
        tfCpf.requestFocus();
    }
    
    public void inserir(){
        try{
            c = new Coordenador();

            c.setCpf(Integer.parseInt(tfCpf.getText()));
            c.setNome(tfNome.getText());
            c.setSetorResponsavel(tfSetor.getText());
            c.setEmailContato(tfEmail.getText());

            c = bd.insereCoo(c);

            if(c != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Coordenador cadastrado com sucesso!",
                        "Cadastro de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Já existe um Coordenador cadastrado com esse CPF!",
                        "Cadastro de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Cadastro de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void consultar(){
        try{
            c = new Coordenador();

            c.setCpf(Integer.parseInt(tfCpf.getText()));

            c = bd.consultaCoo(c);

            if(c != null){
                tfCpf.setText(Integer.toString(c.getCpf()));
                tfNome.setText(c.getNome());
                tfSetor.setText(c.getNome());
                tfEmail.setText(c.getNome());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Coordenador econtrado!",
                        "Consulta de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Consulta de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Consulta de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void alterar(){
        try{
            c = new Coordenador();

            c.setCpf(Integer.parseInt(tfCpf.getText()));

            c = bd.alteraCoo(c);

            if(c != null){
                String nome = JOptionPane.showInputDialog(
                        null,
                        "Informe o novo nome:",
                        "Alteração de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(nome != null){
                    c.setNome(nome);
                }
                
                String setorResponsavel = JOptionPane.showInputDialog(
                        null,
                        "Informe o setor:",
                        "Alteração de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(setorResponsavel != null){
                    c.setSetorResponsavel(setorResponsavel);
                }
                
                String emailContato = JOptionPane.showInputDialog(
                        null,
                        "Informe o Email:",
                        "Alteração de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );

                if(emailContato != null){
                    c.setEmailContato(emailContato);
                }
            }
            
            if(c != null){
                tfCpf.setText(Integer.toString(c.getCpf()));
                tfNome.setText(c.getNome());
                tfSetor.setText(c.getSetorResponsavel());
                tfEmail.setText(c.getEmailContato());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Dados alterados!",
                        "Alteração de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Alteração de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Alteração de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void excluir(){
        try{
            c = new Coordenador();

            c.setCpf(Integer.parseInt(tfCpf.getText()));

            c = bd.excluiCoo(c);

            if(c == null){
                JOptionPane.showMessageDialog(
                        null,
                        "Coordenador excluído com sucesso!",
                        "Exclusão de Coordenador",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Exclusão de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            tfCpf.setText("");
            tfCpf.requestFocus();
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Exclusão de Coordenador - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tabela.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Coordenador c : bd.getBdCoo()){
            modTab.insertRow(posLin, new Object[]{c.getCpf(), c.getNome(), c.getSetorResponsavel(), c.getEmailContato()});
            posLin++;
        }
    }
    
    public void selTab(){
        String valLin = "";
        int posLin = tabela.getSelectedRow();
        for(int col = 0 ; col < tabela.getColumnCount() ; col++){
            valLin += tabela.getModel().getValueAt(posLin, col).toString();
        }
        JOptionPane.showMessageDialog(
                null,
                "O valor da linha é: "+ valLin,
                "Captura de tabela",
                1
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCoordenador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSetor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSetor;
    // End of variables declaration//GEN-END:variables
}
