// Nome: Joao Pedro Dias Elero - RA: 2706431
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormEstudante extends javax.swing.JFrame {
    private Estudante e = new Estudante();
    private BDEstudante bd = BDEstudante.getEstudanteUnic();
    
    private static FormEstudante formEstudanteUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormEstudante.class.getName());

    /**
     * Creates new form FormEstudante
     */
    private FormEstudante() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static FormEstudante getFormEstudanteUnic(){
        if(formEstudanteUnic == null){
            formEstudanteUnic = new FormEstudante();
        }
        return formEstudanteUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabelFaculdade = new javax.swing.JLabel();
        tfFaculdade = new javax.swing.JTextField();
        tfSemestre = new javax.swing.JTextField();
        jLabelSemestre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estudante");

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCpf.setText("CPF:");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNome.setText("Nome:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Faculdade", "Semestre"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabelFaculdade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFaculdade.setText("Faculdade:");

        tfFaculdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFaculdadeActionPerformed(evt);
            }
        });

        tfSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSemestreActionPerformed(evt);
            }
        });

        jLabelSemestre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSemestre.setText("Semestre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelCpf)
                            .addComponent(jLabelFaculdade)
                            .addComponent(jLabelSemestre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addComponent(tfCpf)
                            .addComponent(tfFaculdade)
                            .addComponent(tfSemestre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFaculdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFaculdade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSemestre))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserir();
        lisTab();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        lisTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        lisTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        selTab();
    }//GEN-LAST:event_tabelaMouseClicked

    private void tfFaculdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFaculdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFaculdadeActionPerformed

    private void tfSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSemestreActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        tfCpf.setText("");
        tfNome.setText("");
        tfFaculdade.setText("");
        tfSemestre.setText("");
        tfCpf.requestFocus();
    }
    
    public void inserir(){
        try{
            e = new Estudante();

            e.setCpf(Integer.parseInt(tfCpf.getText()));
            e.setNome(tfNome.getText());
            e.setFaculdadeMatriculada(tfFaculdade.getText());
            e.setSemestre(Integer.parseInt(tfSemestre.getText()));

            e = bd.insereEst(e);

            if(e != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Estudante cadastrado com sucesso!",
                        "Cadastro de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Já existe um Estudante cadastrado com esse CPF!",
                        "Cadastro de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Cadastro de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void consultar(){
        try{
            e = new Estudante();

            e.setCpf(Integer.parseInt(tfCpf.getText()));

            e = bd.consultaEst(e);

            if(e != null){
                tfCpf.setText(Integer.toString(e.getCpf()));
                tfNome.setText(e.getNome());
                tfFaculdade.setText(e.getFaculdadeMatriculada());
                tfSemestre.setText(Integer.toString(e.getSemestre()));
                
                JOptionPane.showMessageDialog(
                        null,
                        "Estudante econtrado!",
                        "Consulta de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Consulta de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Consulta de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void alterar(){
        try{
            e = new Estudante();

            e.setCpf(Integer.parseInt(tfCpf.getText()));

            e = bd.alteraEst(e);

            if(e != null){
                String nome = JOptionPane.showInputDialog(
                        null,
                        "Informe o novo nome:",
                        "Alteração de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(nome != null){
                    e.setNome(nome);
                }
                
                String faculdadeMatriculada = JOptionPane.showInputDialog(
                        null,
                        "Informe a faculdade:",
                        "Alteração de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(faculdadeMatriculada != null){
                    e.setFaculdadeMatriculada(faculdadeMatriculada);
                }
                
                String semestreStr = JOptionPane.showInputDialog(
                        null,
                        "Informe o semestre:",
                        "Alteração de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );

                if(semestreStr != null){
                    try{
                        int semestre = Integer.parseInt(semestreStr);
                        e.setSemestre(semestre);
                    }
                    catch(NumberFormatException nfe){
                        JOptionPane.showMessageDialog(
                            null,
                            "O semestre deve ser um número inteiro!",
                            "Alteração de Estudante - ERRO",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
            }
            
            if(e != null){
                tfCpf.setText(Integer.toString(e.getCpf()));
                tfNome.setText(e.getNome());
                tfFaculdade.setText(e.getFaculdadeMatriculada());
                tfSemestre.setText(Integer.toString(e.getSemestre()));
                
                JOptionPane.showMessageDialog(
                        null,
                        "Dados alterados!",
                        "Alteração de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Alteração de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Alteração de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void excluir(){
        try{
            e = new Estudante();

            e.setCpf(Integer.parseInt(tfCpf.getText()));

            e = bd.excluiEst(e);

            if(e == null){
                JOptionPane.showMessageDialog(
                        null,
                        "Estudante excluída com sucesso!",
                        "Exclusão de Estudante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF não encontrado!",
                        "Exclusão de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            tfCpf.setText("");
            tfCpf.requestFocus();
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O CPF deve ser um número inteiro!",
                        "Exclusão de Estudante - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfCpf.setText("");
                tfCpf.requestFocus();
        }
    }
    
    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tabela.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Estudante e : bd.getBdEst()){
            modTab.insertRow(posLin, new Object[]{e.getCpf(), e.getNome(), e.getFaculdadeMatriculada(), e.getSemestre()});
            posLin++;
        }
    }
    
    public void selTab(){
        String valLin = "";
        int posLin = tabela.getSelectedRow();
        for(int col = 0 ; col < tabela.getColumnCount() ; col++){
            valLin += tabela.getModel().getValueAt(posLin, col).toString();
        }
        JOptionPane.showMessageDialog(
                null,
                "O valor da linha é: "+ valLin,
                "Captura de tabela",
                1
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormEstudante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelFaculdade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfFaculdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSemestre;
    // End of variables declaration//GEN-END:variables
}
