// Nome: Joao Pedro Dias Elero - RA: 2706431
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormFaculdade extends javax.swing.JFrame {
    private Faculdade f = new Faculdade();
    private BDFaculdade bd = BDFaculdade.getFaculdadeUnic();
    
    private static FormFaculdade formFaculdadeUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormFaculdade.class.getName());

    /**
     * Creates new form FormFaculdade
     */
    private FormFaculdade() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static FormFaculdade getFormFaculdadeUnic(){
        if(formFaculdadeUnic == null){
            formFaculdadeUnic = new FormFaculdade();
        }
        return formFaculdadeUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNum = new javax.swing.JLabel();
        tfNum = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabelRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa");

        jLabelNum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNum.setText("Num:");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNome.setText("Nome:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Nome", "Rua"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabelRua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelRua.setText("Rua:");

        tfRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelNum)
                            .addComponent(jLabelRua))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addComponent(tfNum)
                            .addComponent(tfRua)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRua))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserir();
        lisTab();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        lisTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        lisTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        selTab();
    }//GEN-LAST:event_tabelaMouseClicked

    private void tfRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRuaActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        tfNum.setText("");
        tfNome.setText("");
        tfRua.setText("");
        tfNum.requestFocus();
    }
    
    public void inserir(){
        try{
            f = new Faculdade();

            f.setNum(Integer.parseInt(tfNum.getText()));
            f.setNome(tfNome.getText());
            f.setRua(tfRua.getText());

            f = bd.insereFac(f);

            if(f != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Faculdade cadastrada com sucesso!",
                        "Cadastro de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Já existe uma Faculdade cadastrada com esse ID!",
                        "Cadastro de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O número deve ser um inteiro!",
                        "Cadastro de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
        }
    }
    
    public void consultar(){
        try{
            f = new Faculdade();

            f.setNum(Integer.parseInt(tfNum.getText()));

            f = bd.consultaFac(f);

            if(f != null){
                tfNum.setText(Integer.toString(f.getNum()));
                tfNome.setText(f.getNome());
                tfRua.setText(f.getRua());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Faculdade encontrada!",
                        "Consulta de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Número não encontrado!",
                        "Consulta de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O número deve ser um inteiro!",
                        "Consulta de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
        }
    }
    
    public void alterar(){
        try{
            f = new Faculdade();

            f.setNum(Integer.parseInt(tfNum.getText()));

            f = bd.alteraFac(f);

            if(f != null){
                String nome = JOptionPane.showInputDialog(
                        null,
                        "Informe o novo nome:",
                        "Alteração de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(nome != null){
                    f.setNome(nome);
                }
            }
            
            if(f != null){
                String rua = JOptionPane.showInputDialog(
                        null,
                        "Informe a nova rua:",
                        "Alteração de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                if(rua != null){
                    f.setRua(rua);
                }
            }
            
            if(f != null){
                tfNum.setText(Integer.toString(f.getNum()));
                tfNome.setText(f.getNome());
                tfRua.setText(f.getRua());
                
                JOptionPane.showMessageDialog(
                        null,
                        "Dados alterados!",
                        "Alteração de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Número não encontrado!",
                        "Alteração de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O número deve ser um inteiro!",
                        "Alteração de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
        }
    }
    
    public void excluir(){
        try{
            f = new Faculdade();

            f.setNum(Integer.parseInt(tfNum.getText()));

            f = bd.excluiFac(f);

            if(f == null){
                JOptionPane.showMessageDialog(
                        null,
                        "Faculdade excluída com sucesso!",
                        "Exclusão de Faculdade",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Número não encontrado!",
                        "Exclusão de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            tfNum.setText("");
            tfNum.requestFocus();
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        null,
                        "O número deve ser um inteiro!",
                        "Exclusão de Faculdade - ERRO",
                        JOptionPane.ERROR_MESSAGE
                );
                tfNum.setText("");
                tfNum.requestFocus();
        }
    }
    
    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tabela.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Faculdade f : bd.getBdFac()){
            modTab.insertRow(posLin, new Object[]{f.getNum(), f.getNome(), f.getRua()});
            posLin++;
        }
    }
    
    public void selTab(){
        String valLin = "";
        int posLin = tabela.getSelectedRow();
        for(int col = 0 ; col < tabela.getColumnCount() ; col++){
            valLin += tabela.getModel().getValueAt(posLin, col).toString();
        }
        JOptionPane.showMessageDialog(
                null,
                "O valor da linha é: "+ valLin,
                "Captura de tabela",
                1
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormFaculdade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNum;
    private javax.swing.JTextField tfRua;
    // End of variables declaration//GEN-END:variables
}
